---
- become: false
  hosts: group
  name: "win-connection check"
  gather_facts: false

  tasks:
    - name: Pull logs from azure storage
      win_command: powershell.exe -ExecutionPolicy ByPass -File G:\pssis-outage-scripts\Scripts\RCA\PullLogsfromAzure.ps1 {{FSTicket}}
      register: host_output
      
    
    - debug:
        msg: {{hostvars['group'].temp2}}
