---
- become: false
  hosts: windows
  name: "win-connection check"
  gather_facts: false
  tasks:
    - name: Run remote PowerShell Script
      ansible.windows.win_powershell:
        script: G:\pssis-outage-scripts\Scripts\RCA\PullLogsfromAzure.ps1
        parameters: 
          FSTicket: 782594
