---
- become: false
  hosts: all
  name: "win-connection check"
  gather_facts: false
  tasks:
    - name: Run remote PowerShell Script
      win_command: powershell.exe -ExecutionPolicy ByPass -File G:\pssis-outage-scripts\Scripts\RCA\PullLogsfromAzure.ps1 782594
